<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CharacterSeeder extends Seeder
{
    use WithoutModelEvents;

    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $roles = DB::table('character_roles')->pluck('id', 'name');

        // Compatibility fallback in case role table still uses "Ranged" naming.
        if (!isset($roles['Ranged DPS']) && isset($roles['Ranged'])) {
            $roles['Ranged DPS'] = $roles['Ranged'];
        }

        $requiredRoles = ['Tank', 'Assassin', 'Mage', 'Ranged DPS', 'Support'];
        $missingRoles = array_values(array_filter($requiredRoles, fn ($role) => !isset($roles[$role])));
        if (!empty($missingRoles)) {
            throw new \RuntimeException('Missing character roles: ' . implode(', ', $missingRoles));
        }

        $now = now();

        $characters = [
            // Tank (6)
            [
                'name' => 'Iron Titan',
                'description' => 'Frontline tank with extreme durability.',
                'base_price' => 200,
                'hp' => 1250,
                'damage' => 85,
                'speed' => 1.0,
                'range' => 1,
                'cooldown' => 2.4,
                'abilities' => json_encode(['special_ability' => 'Shield Wall (40% dmg reduction for 5s)']),
                'character_role_id' => $roles['Tank'],
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Stone Guardian',
                'description' => 'Defensive protector that controls enemy focus.',
                'base_price' => 180,
                'hp' => 1150,
                'damage' => 95,
                'speed' => 1.2,
                'range' => 1,
                'cooldown' => 2.3,
                'abilities' => json_encode(['special_ability' => 'Taunt (forces enemies to target for 4s)']),
                'character_role_id' => $roles['Tank'],
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Flame Golem',
                'description' => 'Burning tank that punishes enemies on defeat.',
                'base_price' => 190,
                'hp' => 1050,
                'damage' => 110,
                'speed' => 1.0,
                'range' => 1,
                'cooldown' => 2.2,
                'abilities' => json_encode(['special_ability' => 'Explodes on death (200 AoE damage)']),
                'character_role_id' => $roles['Tank'],
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Thunder Rhino',
                'description' => 'Charging bruiser that opens with a heavy strike.',
                'base_price' => 210,
                'hp' => 1200,
                'damage' => 100,
                'speed' => 1.5,
                'range' => 1,
                'cooldown' => 2.1,
                'abilities' => json_encode(['special_ability' => 'Charge (double damage first hit)']),
                'character_role_id' => $roles['Tank'],
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Steel Samurai',
                'description' => 'Balanced tank with reactive counter potential.',
                'base_price' => 170,
                'hp' => 950,
                'damage' => 120,
                'speed' => 1.3,
                'range' => 1,
                'cooldown' => 2.0,
                'abilities' => json_encode(['special_ability' => 'Counter Strike (returns 25% damage)']),
                'character_role_id' => $roles['Tank'],
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Void Colossus',
                'description' => 'Slow but massive tank with periodic shielding.',
                'base_price' => 230,
                'hp' => 1300,
                'damage' => 80,
                'speed' => 0.9,
                'range' => 1,
                'cooldown' => 2.5,
                'abilities' => json_encode(['special_ability' => 'Absorbs 200 damage shield every 10s']),
                'character_role_id' => $roles['Tank'],
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Assassin (6)
            [
                'name' => 'Shadow Reaper',
                'description' => 'High-burst assassin that hunts weak targets.',
                'base_price' => 220,
                'hp' => 450,
                'damage' => 220,
                'speed' => 2.5,
                'range' => 1,
                'cooldown' => 0.9,
                'abilities' => json_encode(['special_ability' => 'Teleport behind lowest HP enemy']),
                'character_role_id' => $roles['Assassin'],
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Night Blade',
                'description' => 'Critical-focused assassin with reliable burst.',
                'base_price' => 180,
                'hp' => 500,
                'damage' => 190,
                'speed' => 2.2,
                'range' => 1,
                'cooldown' => 1.0,
                'abilities' => json_encode(['special_ability' => '30% chance double damage']),
                'character_role_id' => $roles['Assassin'],
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Phantom Dash',
                'description' => 'Fast engager that slices through enemy lines.',
                'base_price' => 200,
                'hp' => 420,
                'damage' => 210,
                'speed' => 3.0,
                'range' => 1,
                'cooldown' => 0.8,
                'abilities' => json_encode(['special_ability' => 'Dash through enemies']),
                'character_role_id' => $roles['Assassin'],
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Venom Striker',
                'description' => 'Poison assassin with sustained damage-over-time.',
                'base_price' => 170,
                'hp' => 480,
                'damage' => 175,
                'speed' => 2.0,
                'range' => 1,
                'cooldown' => 1.1,
                'abilities' => json_encode(['special_ability' => 'Poison (30 dmg/sec for 5s)']),
                'character_role_id' => $roles['Assassin'],
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Crimson Fang',
                'description' => 'Bleed specialist with strong single-target pressure.',
                'base_price' => 210,
                'hp' => 470,
                'damage' => 215,
                'speed' => 2.3,
                'range' => 1,
                'cooldown' => 0.95,
                'abilities' => json_encode(['special_ability' => 'Bleed (extra 100 over 4s)']),
                'character_role_id' => $roles['Assassin'],
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Silent Specter',
                'description' => 'Stealth opener with lethal early engagement.',
                'base_price' => 240,
                'hp' => 410,
                'damage' => 230,
                'speed' => 2.8,
                'range' => 1,
                'cooldown' => 0.85,
                'abilities' => json_encode(['special_ability' => 'Invisible for 3s at start']),
                'character_role_id' => $roles['Assassin'],
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Mage (6)
            [
                'name' => 'Arcane Wizard',
                'description' => 'AoE caster with explosive magical burst.',
                'base_price' => 210,
                'hp' => 620,
                'damage' => 170,
                'speed' => 1.5,
                'range' => 3,
                'cooldown' => 1.5,
                'abilities' => json_encode(['special_ability' => 'Fireball (180 AoE damage)']),
                'character_role_id' => $roles['Mage'],
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Frost Queen',
                'description' => 'Control mage that freezes enemies in place.',
                'base_price' => 200,
                'hp' => 650,
                'damage' => 155,
                'speed' => 1.4,
                'range' => 3,
                'cooldown' => 1.6,
                'abilities' => json_encode(['special_ability' => 'Freeze (stuns 2s)']),
                'character_role_id' => $roles['Mage'],
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Storm Caller',
                'description' => 'Chain-lightning specialist for grouped enemies.',
                'base_price' => 220,
                'hp' => 600,
                'damage' => 175,
                'speed' => 1.6,
                'range' => 3,
                'cooldown' => 1.45,
                'abilities' => json_encode(['special_ability' => 'Lightning Chain (hits 3 enemies)']),
                'character_role_id' => $roles['Mage'],
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Dark Sorcerer',
                'description' => 'Sustain mage that drains life from enemies.',
                'base_price' => 190,
                'hp' => 630,
                'damage' => 165,
                'speed' => 1.5,
                'range' => 4,
                'cooldown' => 1.55,
                'abilities' => json_encode(['special_ability' => 'Life Drain (heals 50% damage dealt)']),
                'character_role_id' => $roles['Mage'],
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Inferno Sage',
                'description' => 'Damage-over-time mage with fire control zones.',
                'base_price' => 230,
                'hp' => 580,
                'damage' => 200,
                'speed' => 1.4,
                'range' => 3,
                'cooldown' => 1.6,
                'abilities' => json_encode(['special_ability' => 'Burn zone (50 dmg/sec AoE)']),
                'character_role_id' => $roles['Mage'],
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Chrono Mystic',
                'description' => 'Temporal mage that disrupts enemy timings.',
                'base_price' => 210,
                'hp' => 610,
                'damage' => 150,
                'speed' => 1.6,
                'range' => 4,
                'cooldown' => 1.5,
                'abilities' => json_encode(['special_ability' => 'Reduces enemy cooldowns by 50%']),
                'character_role_id' => $roles['Mage'],
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Ranged DPS (6)
            [
                'name' => 'Elite Archer',
                'description' => 'Rapid ranged attacker with burst volleys.',
                'base_price' => 170,
                'hp' => 650,
                'damage' => 150,
                'speed' => 1.8,
                'range' => 4,
                'cooldown' => 1.3,
                'abilities' => json_encode(['special_ability' => 'Rapid Shot (3 arrow burst)']),
                'character_role_id' => $roles['Ranged DPS'],
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Crossbow Sniper',
                'description' => 'Long-range specialist with execution bonus.',
                'base_price' => 220,
                'hp' => 600,
                'damage' => 190,
                'speed' => 1.2,
                'range' => 5,
                'cooldown' => 1.4,
                'abilities' => json_encode(['special_ability' => 'Headshot bonus to low HP']),
                'character_role_id' => $roles['Ranged DPS'],
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Gunner Mech',
                'description' => 'Mechanical ranged unit that slows enemies.',
                'base_price' => 180,
                'hp' => 750,
                'damage' => 135,
                'speed' => 1.5,
                'range' => 3,
                'cooldown' => 1.6,
                'abilities' => json_encode(['special_ability' => 'Reduces enemy speed']),
                'character_role_id' => $roles['Ranged DPS'],
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Spear Valkyrie',
                'description' => 'Hybrid ranged striker with piercing attacks.',
                'base_price' => 160,
                'hp' => 700,
                'damage' => 145,
                'speed' => 1.7,
                'range' => 2,
                'cooldown' => 1.35,
                'abilities' => json_encode(['special_ability' => 'Pierces 2 enemies']),
                'character_role_id' => $roles['Ranged DPS'],
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Blaze Rifleman',
                'description' => 'Marksman with splash damage ammunition.',
                'base_price' => 200,
                'hp' => 620,
                'damage' => 175,
                'speed' => 1.6,
                'range' => 4,
                'cooldown' => 1.25,
                'abilities' => json_encode(['special_ability' => 'Explosive bullets (small AoE)']),
                'character_role_id' => $roles['Ranged DPS'],
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Wind Ranger',
                'description' => 'Agile ranged attacker with accelerated firing.',
                'base_price' => 190,
                'hp' => 600,
                'damage' => 165,
                'speed' => 2.0,
                'range' => 4,
                'cooldown' => 1.2,
                'abilities' => json_encode(['special_ability' => 'Increased attack speed']),
                'character_role_id' => $roles['Ranged DPS'],
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Support (6)
            [
                'name' => 'Divine Healer',
                'description' => 'Primary healer that sustains team health.',
                'base_price' => 200,
                'hp' => 700,
                'damage' => 90,
                'speed' => 1.4,
                'range' => 3,
                'cooldown' => 1.6,
                'abilities' => json_encode(['special_ability' => 'Heals ally 150 HP every 5s']),
                'character_role_id' => $roles['Support'],
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Battle Bard',
                'description' => 'Offensive buffer that amplifies team damage.',
                'base_price' => 180,
                'hp' => 650,
                'damage' => 80,
                'speed' => 1.6,
                'range' => 3,
                'cooldown' => 1.4,
                'abilities' => json_encode(['special_ability' => 'Increase team damage by 20%']),
                'character_role_id' => $roles['Support'],
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Time Mage',
                'description' => 'Control support that slows enemy advances.',
                'base_price' => 190,
                'hp' => 620,
                'damage' => 110,
                'speed' => 1.5,
                'range' => 3,
                'cooldown' => 1.45,
                'abilities' => json_encode(['special_ability' => 'Slows enemies in radius']),
                'character_role_id' => $roles['Support'],
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Guardian Priest',
                'description' => 'Defensive support providing shields to allies.',
                'base_price' => 210,
                'hp' => 750,
                'damage' => 70,
                'speed' => 1.3,
                'range' => 3,
                'cooldown' => 1.7,
                'abilities' => json_encode(['special_ability' => 'Grants 150 shield to allies']),
                'character_role_id' => $roles['Support'],
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Energy Alchemist',
                'description' => 'Utility support boosting ally movement speed.',
                'base_price' => 180,
                'hp' => 650,
                'damage' => 100,
                'speed' => 1.7,
                'range' => 3,
                'cooldown' => 1.5,
                'abilities' => json_encode(['special_ability' => 'Boosts speed by 30%']),
                'character_role_id' => $roles['Support'],
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Spirit Summoner',
                'description' => 'Summoning support with temporary battlefield aid.',
                'base_price' => 220,
                'hp' => 680,
                'damage' => 120,
                'speed' => 1.4,
                'range' => 3,
                'cooldown' => 1.55,
                'abilities' => json_encode(['special_ability' => 'Summons temporary minion']),
                'character_role_id' => $roles['Support'],
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];

        DB::table('characters')->whereIn('name', array_column($characters, 'name'))->delete();
        DB::table('characters')->insert($characters);
    }
}
